Add missing runtime dependency on setuptools
Found while running Enos in a poetry-managed virtualenv:

    File "/home/bjonglez/.cache/pypoetry/virtualenvs/enos-3_2QLl3d-py3.11/lib/python3.11/site-packages/enoslib/html/__init__.py", line 6, in <module>
      import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'